buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:8.13.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.20"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven {
            url 'https://jitpack.io'
        }
        maven {
            url 'https://artifacts.applovin.com/android'
        }
    }

    gradle.projectsEvaluated {
        tasks.withType(JavaCompile).tap {
            configureEach {
                options.compilerArgs << "-Xlint:unchecked"
            }
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
