org.gradle.jvmargs=-Xmx2048m
org.gradle.java.home=/Users/loitran/Library/Java/JavaVirtualMachines/jbr-17.0.14/Contents/Home
kotlin.code.style=official
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.useAndroidX=true
android.enableJetifier=true
KS_ALIAS=mckimquyen
KS_PW=27072000

# AppLovin MAX
APPLOVIN_SDK_KEY=e75FnQfS9XTTqM1Kne69U7PW_MBgAnGQTFvtwVVui6kRPKs5L7ws9twr5IQWwVfzPKZ5pF2IfDa7lguMgGlCyt
APPLOVIN_BANNER_ID=84d187d1b08adc3d
APPLOVIN_INTERSTITIAL_ID=5ac61198c318d67b
APPLOVIN_APP_OPEN_ID=6569037b86c0256e
APPLOVIN_REWARDED_ID=671ca9067e78cc47

# AdMob — release (real units)
ADMOB_BANNER_ID_RELEASE=ca-app-pub-3612191981543807/9127422654
ADMOB_INTERSTITIAL_ID_RELEASE=ca-app-pub-3612191981543807/7814340985
ADMOB_APP_OPEN_ID_RELEASE=ca-app-pub-3612191981543807/3616361085

# AdMob — debug (Google test units)
ADMOB_BANNER_ID_DEBUG=ca-app-pub-3940256099942544/6300978111
ADMOB_INTERSTITIAL_ID_DEBUG=ca-app-pub-3940256099942544/1033173712
ADMOB_APP_OPEN_ID_DEBUG=ca-app-pub-3940256099942544/9257395921
